<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AdventureWorksController.cs" />
    <Compile Remove="Controllers\ASyncPersonsController.cs" />
    <Compile Remove="Controllers\ASyncValuesController.cs" />
    <Compile Remove="Controllers\KPWCFServiceClientController.cs" />
    <Compile Remove="Controllers\PersonsController.cs" />
    <Compile Remove="Controllers\ValuesController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Literature\" />
  </ItemGroup>

</Project>
